# -*- coding: utf-8 -*-
"""Rock-Paper-Scissor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uhyAWH79W9PcIeD2bOL2j0O_AMR6rC7u
"""

import random
print("let's play Rock - Paper - Scissor")
user_action=input("enter your choice(rock,paper,scissor): ")
possible_action=["rock","paper","scissor"]
if user_action not in possible_action:
  print("please enter a valid response (rock,paper,scissor): ")
else:
  computer_action=random.choice(possible_action)
  print(f'\nyou chose {user_action},computer chose {computer_action}')

  if user_action ==computer_action:
    print(f"both players selected {user_action}. its tie👀")
  elif user_action=="rock":
    if computer_action=="scissor":
      print("Rock smashes Scissor, you win🥳")
    else:
      print("Paper covers Rock,you lose🙃")
  elif user_action== "paper":
    if computer_action=="rock":
     print("Paper covers Rock,you win🥳")
    else:
      print("Scissor cut Paper, you lose🙃")
  else:
   if computer_action=='paper':
     print("Scissor cut the Paper, you win🥳")
   else:
     print("Rock smashes the Scissor,you lose🙃")

